GET http://localhost:8000/api/product
###

GET http://localhost:8000/api/product/1
###

POST http://localhost:8000/api/product
Content-Type: application/json

{
    "name": "",
    "price": ""
}
###

PUT http://localhost:8000/api/product/27
Content-Type: application/json

{
    "price": 40
}
###

DELETE http://localhost:8000/api/product/23
